# Generated by Django 2.0.5 on 2019-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_database',
            field=models.CharField(blank=True, default='testconn', max_length=100, null=True, verbose_name='数据库库名'),
        ),
    ]
