# Generated by Django 2.0.5 on 2019-12-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0002_auto_20191204_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_biao',
            field=models.CharField(blank=True, default='testdatas_clickandback', max_length=1000, null=True, verbose_name='数据库中的表'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_tiaojianzhi',
            field=models.CharField(blank=True, default='10', max_length=1000, null=True, verbose_name='where条件字段值'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_tiaojianziduan',
            field=models.CharField(blank=True, default='id', max_length=100, null=True, verbose_name='where条件字段名'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_xiugaihoudezhi',
            field=models.CharField(blank=True, default='修改后的油烟餐饮', max_length=1000, null=True, verbose_name='数据库中的表的字段修改后的值'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_xiugaiqiandezhi',
            field=models.CharField(blank=True, default='/html/body/', max_length=1000, null=True, verbose_name='数据库中的表的字段修改前的值'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_ziduan',
            field=models.CharField(blank=True, default='current_page_click_ele_find_value', max_length=1000, null=True, verbose_name='数据库中的表的字段名'),
        ),
    ]
