# Generated by Django 2.0.5 on 2019-12-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0003_auto_20191204_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_xiugaihoudezhi',
            field=models.CharField(blank=True, default='修改后的油烟餐饮', max_length=1000, null=True, verbose_name='数据库中的表的字段替换后的值'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_xiugaiqiandezhi',
            field=models.CharField(blank=True, default='/html/body/', max_length=1000, null=True, verbose_name='数据库中的表的字段替换前的值'),
        ),
    ]
