# Generated by Django 2.0.5 on 2019-12-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0005_auto_20191205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_biao',
            field=models.CharField(blank=True, default='testdatas_clickandback', help_text='多个表之间以英文半角逗号(,)隔开', max_length=1000, null=True, verbose_name='数据库中的表'),
        ),
    ]
