# Generated by Django 2.0.5 on 2019-12-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testupdatadb', '0006_auto_20191205_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_tiaojianzhi',
            field=models.CharField(blank=True, default='10', help_text="多个条件字段值之间以英文半角逗号(,)隔开，如果是遍历所有，请填写'all'", max_length=1000, null=True, verbose_name='where条件字段值'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_tiaojianziduan',
            field=models.CharField(blank=True, default='id', help_text='多个条件字段之间以英文半角逗号(,)隔开', max_length=100, null=True, verbose_name='where条件字段名'),
        ),
        migrations.AlterField(
            model_name='updatedbdata',
            name='db_ziduan',
            field=models.CharField(blank=True, default='current_page_click_ele_find_value', help_text='多个字段之间以英文半角逗号(,)隔开', max_length=1000, null=True, verbose_name='数据库中的表的字段名'),
        ),
    ]
