# Generated by Django 2.0.5 on 2019-10-22 15:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testproject', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('testmodule', models.CharField(default='', max_length=100, verbose_name='测试模块')),
                ('testcasetitle', models.CharField(default='', max_length=100, verbose_name='测试内容的名称')),
                ('teststarttime', models.CharField(default='', max_length=100, verbose_name='开始运行时间')),
                ('forcount', models.CharField(default='', max_length=100, verbose_name='第几次循环')),
                ('response_status_code', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='接口响应status_code')),
                ('response_text', models.TextField(blank=True, default='', null=True, verbose_name='接口响应text')),
                ('response_content', models.TextField(blank=True, default='', null=True, verbose_name='接口响应content')),
                ('response_elapsed', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='接口响应elapsed')),
                ('response_elapsed_microseconds', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='接口响应elapsed_microseconds(单位：微秒)')),
                ('response_headers', models.TextField(blank=True, default='', null=True, verbose_name='接口响应headers')),
                ('response_cookies', models.TextField(blank=True, default='', null=True, verbose_name='接口响应cookies')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接口测试结果统计',
                'verbose_name_plural': '接口测试结果统计',
            },
        ),
    ]
