# Generated by Django 2.0.5 on 2019-11-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reportdatas', '0008_pageloadtimereportfivesecond_pageloadtimereportfoursecond_pageloadtimereportonesecond_pageloadtimere'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PageLoadTimeReportFiveSecond',
        ),
        migrations.DeleteModel(
            name='PageLoadTimeReportFourSecond',
        ),
        migrations.DeleteModel(
            name='PageLoadTimeReportOneSecond',
        ),
        migrations.DeleteModel(
            name='PageLoadTimeReportThereSecond',
        ),
        migrations.DeleteModel(
            name='PageLoadTimeReportTwoSecond',
        ),
    ]
