# Generated by Django 2.0.5 on 2019-10-22 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0003_auto_20191022_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestdata',
            name='is_use_cache',
            field=models.BooleanField(default=True, verbose_name='是否使用缓存cookies'),
        ),
    ]
