# Generated by Django 2.0.5 on 2019-10-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0004_auto_20191022_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestheaders',
            name='auto_input_long',
        ),
        migrations.RemoveField(
            model_name='requestheaders',
            name='auto_input_type',
        ),
        migrations.RemoveField(
            model_name='requestheaders',
            name='is_auto_input',
        ),
        migrations.RemoveField(
            model_name='requestheaders',
            name='is_check',
        ),
        migrations.RemoveField(
            model_name='requestheaders',
            name='is_with_time',
        ),
    ]
