# Generated by Django 2.0.5 on 2019-10-22 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0005_auto_20191022_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestdatas',
            name='is_check',
            field=models.BooleanField(default=False, verbose_name='是否进行验证'),
        ),
        migrations.AlterField(
            model_name='requestdatas',
            name='is_with_time',
            field=models.BooleanField(default=False, verbose_name='是否带时间串'),
        ),
    ]
