# Generated by Django 2.0.5 on 2019-10-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapidatas', '0006_auto_20191022_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequestdata',
            name='test_page',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试页面'),
        ),
    ]
