# Generated by Django 2.0.5 on 2019-09-05 15:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickAndBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('test_case_title', models.CharField(default='', max_length=200, verbose_name='测试内容的名称')),
                ('is_run_case', models.BooleanField(default=True, verbose_name='是否运行')),
                ('current_page_click_ele_find', models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='当前页面要点击元素查找风格')),
                ('current_page_click_ele_find_value', models.CharField(default='', max_length=1000, verbose_name='当前页面要点击元素查找风格的确切值')),
                ('is_new', models.BooleanField(default=False, verbose_name='是否新窗口')),
                ('next_page_check_ele_find', models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='下一页面标识元素查找风格')),
                ('next_page_check_ele_find_value', models.CharField(default='', max_length=1000, verbose_name='下一页面要点击元素查找风格的确切值')),
                ('case_counts', models.IntegerField(default='1', help_text='用例循环次数，请填写数字，例如：1、2、3', verbose_name='用例循环次数')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('depend_case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的前置用例')),
            ],
            options={
                'verbose_name': '点击返回场景',
                'verbose_name_plural': '点击返回场景',
            },
        ),
    ]
