# Generated by Django 2.0.5 on 2019-09-05 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdatas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickandback',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeuser', to=settings.AUTH_USER_MODEL, verbose_name='添加用例人'),
        ),
    ]
