# Generated by Django 2.0.5 on 2019-09-09 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0003_auto_20190909_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickandback',
            name='case_counts',
            field=models.IntegerField(default='1', help_text='循环次数，请填写数字，例如：1、2、3', verbose_name='循环次数'),
        ),
        migrations.AlterField(
            model_name='clickandback',
            name='write_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='writeuser', to=settings.AUTH_USER_MODEL, verbose_name='添加人'),
        ),
    ]
