# Generated by Django 2.0.5 on 2019-09-16 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0005_auto_20190913_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaddandcheck',
            name='is_signel_page',
            field=models.BooleanField(default=False, verbose_name='是否单页面'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='page_number_xpath',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='页数层xpath路径值'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='result_table_ele_find',
            field=models.CharField(default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, verbose_name='结果表格查找风格'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='result_table_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='结果表格查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='newaddandcheck',
            name='table_colnum_counts',
            field=models.CharField(default='', help_text='结果表格总列数，请填写数字，例如：1、2、3', max_length=100, verbose_name='结果表格列数'),
        ),
    ]
