# Generated by Django 2.0.5 on 2019-09-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0008_inputtapinputfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtapinputtext',
            name='is_with_time',
            field=models.BooleanField(default=True, verbose_name='是否带时间串'),
        ),
    ]
