# Generated by Django 2.0.5 on 2019-09-18 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0009_inputtapinputtext_is_with_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inputtapinputfile',
            options={'verbose_name': '文件输入框相关内容', 'verbose_name_plural': '文件输入框相关内容'},
        ),
        migrations.AlterModelOptions(
            name='inputtapinputtext',
            options={'verbose_name': '文本输入框相关内容', 'verbose_name_plural': '文本输入框相关内容'},
        ),
        migrations.AlterModelOptions(
            name='selecttapselectoption',
            options={'verbose_name': '选项框及相关内容', 'verbose_name_plural': '选项框及相关内容'},
        ),
    ]
