# Generated by Django 2.0.5 on 2019-09-18 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0010_auto_20190918_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecttapselectoption',
            options={'verbose_name': '选项框相关内容', 'verbose_name_plural': '选项框相关内容'},
        ),
    ]
