# Generated by Django 2.0.5 on 2019-09-18 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0011_auto_20190918_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='selecttapselecttext',
            options={'verbose_name': '选项框及选项文本内容', 'verbose_name_plural': '选项框及选项文本内容'},
        ),
        migrations.AlterField(
            model_name='inputtapinputfile',
            name='input_class_name',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='隐藏输入框的类名'),
        ),
        migrations.AlterField(
            model_name='inputtapinputfile',
            name='input_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='输入框查找风格'),
        ),
        migrations.AlterField(
            model_name='inputtapinputfile',
            name='input_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='输入框查找风格的确切值'),
        ),
        migrations.AlterField(
            model_name='inputtapinputfile',
            name='input_file',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='输入框中要输入的文件路径'),
        ),
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='input_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='输入框查找风格'),
        ),
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='input_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='输入框查找风格的确切值'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='select_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='选项框的查找风格'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='select_option_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='选项的查找风格'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='select_option_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='选项查找风格的确切值'),
        ),
        migrations.AlterField(
            model_name='selecttapselecttext',
            name='select_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='选项框的查找风格'),
        ),
        migrations.AlterField(
            model_name='selecttapselecttext',
            name='select_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='选项框查找风格的确切值'),
        ),
        migrations.AlterField(
            model_name='selecttapselecttext',
            name='select_option_text',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='选项的文本的内容'),
        ),
    ]
