# Generated by Django 2.0.5 on 2019-09-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0012_auto_20190918_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='input_text',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='输入框中要输入的内容'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='select_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='选项框查找风格的确切值'),
        ),
    ]
