# Generated by Django 2.0.5 on 2019-09-18 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0014_auto_20190918_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaddandcheck',
            name='result_table_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='结果表格查找风格'),
        ),
        migrations.AlterField(
            model_name='newaddandcheck',
            name='table_colnum_counts',
            field=models.CharField(blank=True, default='', help_text='结果表格总列数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='结果表格列数'),
        ),
    ]
