# Generated by Django 2.0.5 on 2019-09-19 10:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0016_inputtapinputdatetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioAndReelectionLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='选项标签查找风格')),
                ('label_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='选项标签查找风格的确切值')),
                ('is_check', models.BooleanField(default=True, verbose_name='是否选中')),
                ('checked_add_attribute', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='元素被选中后新增的属性')),
                ('checked_add_attribute_value', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='元素被选中后新增的属性的值')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('newaddandcheck', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景')),
            ],
            options={
                'verbose_name': '单选项和复选项相关内容',
                'verbose_name_plural': '单选项和复选项相关内容',
            },
        ),
    ]
