# Generated by Django 2.0.5 on 2019-09-19 13:21

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdatas', '0017_radioandreelectionlabel'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchAndCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('test_case_title', models.CharField(default='', max_length=200, verbose_name='测试内容的名称')),
                ('is_run_case', models.BooleanField(default=True, verbose_name='是否运行')),
                ('serach_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='查询按钮查找风格')),
                ('search_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='查询按钮查找风格的确切值')),
                ('result_table_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='结果表格查找风格')),
                ('result_table_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='结果表格查找风格的确切值')),
                ('table_colnum_counts', models.CharField(blank=True, default='', help_text='结果表格总列数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='结果表格列数')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('depend_click_case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的点击场景的用例')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '新增场景',
                'verbose_name_plural': '新增场景',
            },
        ),
    ]
