# Generated by Django 2.0.5 on 2019-09-19 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0018_searchandcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchandcheck',
            options={'verbose_name': '查询场景', 'verbose_name_plural': '查询场景'},
        ),
    ]
