# Generated by Django 2.0.5 on 2019-09-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0019_auto_20190919_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtapinputtext',
            name='searchandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.SearchAndCheck', verbose_name='依赖的搜素场景'),
        ),
        migrations.AddField(
            model_name='selecttapselectoption',
            name='searchandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.SearchAndCheck', verbose_name='依赖的搜素场景'),
        ),
    ]
