# Generated by Django 2.0.5 on 2019-09-19 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0022_auto_20190919_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchselecttapselectoption',
            name='newaddandcheck',
        ),
    ]
