# Generated by Django 2.0.5 on 2019-09-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0023_remove_searchselecttapselectoption_newaddandcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchandcheck',
            name='is_with_date',
            field=models.BooleanField(default=True, verbose_name='是否查询到数据'),
        ),
    ]
