# Generated by Django 2.0.5 on 2019-09-19 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0024_searchandcheck_is_with_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchandcheck',
            old_name='serach_ele_find',
            new_name='search_ele_find',
        ),
        migrations.RemoveField(
            model_name='searchandcheck',
            name='table_colnum_counts',
        ),
    ]
