# Generated by Django 2.0.5 on 2019-09-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0025_auto_20190919_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchselecttapselectoption',
            name='search_result_colnum',
            field=models.CharField(blank=True, default='', help_text='在搜索结果表格中对应的列数，请填写数字，例如：1、2、3...;如果是多列，列数之间以半角逗号隔开，例如：3,4', max_length=100, null=True, verbose_name='在搜索结果表格中对应的列数'),
        ),
    ]
