# Generated by Django 2.0.5 on 2019-09-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0027_auto_20190919_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaddandcheck',
            name='table_colnum_counts',
            field=models.CharField(blank=True, default='', help_text='结果表格总列数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='结果表格总列数'),
        ),
    ]
