# Generated by Django 2.0.5 on 2019-09-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0028_auto_20190920_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtapinputtext',
            name='is_check',
            field=models.BooleanField(default=True, verbose_name='是否进行验证'),
        ),
    ]
