# Generated by Django 2.0.5 on 2019-09-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0030_auto_20190927_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtapinputtext',
            name='auto_input_long',
            field=models.IntegerField(default='1', help_text='字符的个数，请填写数字，例如：1、2、3', verbose_name='自动输入的字符的个数'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='auto_input_type',
            field=models.CharField(choices=[(1, '数字'), (2, '字母'), (3, '数字和字母'), (4, '数字和字母和特殊符号'), (5, '数字和字母和特殊符号和转义字符'), (6, '汉字')], default=0, max_length=1, verbose_name='自动输入字符的类型'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='is_auto_input',
            field=models.BooleanField(default=False, verbose_name='是否自动输入'),
        ),
    ]
