# Generated by Django 2.0.5 on 2019-09-29 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0031_auto_20190929_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='auto_input_type',
            field=models.CharField(blank=True, choices=[(1, '数字'), (2, '字母'), (3, '数字和字母'), (4, '数字和字母和特殊符号'), (5, '数字和字母和特殊符号和转义字符'), (6, '汉字')], default=1, max_length=1, null=True, verbose_name='自动输入字符的类型'),
        ),
    ]
