# Generated by Django 2.0.5 on 2019-09-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0032_auto_20190929_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='auto_input_long',
            field=models.IntegerField(blank=True, default='1', help_text='字符的个数，请填写数字，例如：1、2、3', null=True, verbose_name='自动输入的字符的个数'),
        ),
    ]
