# Generated by Django 2.0.5 on 2019-09-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0034_auto_20190929_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='auto_input_long',
            field=models.CharField(blank=True, default='1', help_text='字符的个数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='自动输入的字符的个数'),
        ),
    ]
