# Generated by Django 2.0.5 on 2019-09-29 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0035_auto_20190929_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputfile',
            name='input_file',
            field=models.CharField(blank=True, default='', help_text='多个文件路径之间以半角逗号隔开,例如“D:\timg.jpg,/root/timg.jpg”，会获取第一个有效路径', max_length=300, null=True, verbose_name='输入框中要输入的文件路径'),
        ),
    ]
