# Generated by Django 2.0.5 on 2019-09-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0039_auto_20190930_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickandback',
            name='next_page_check_ele_find_value',
            field=models.CharField(default='', max_length=1000, verbose_name='下一页面标识元素查找风格的确切值'),
        ),
    ]
