# Generated by Django 2.0.5 on 2019-10-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0040_auto_20190930_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaddandcheck',
            name='case_priority',
            field=models.CharField(blank=True, choices=[('P0', '冒烟用例'), ('P1', '系统的重要功能用例'), ('P2', '系统的一般功能用例'), ('P3', '极低级别的用例')], default='P1', max_length=10, null=True, verbose_name='用例优先级'),
        ),
        migrations.AddField(
            model_name='searchandcheck',
            name='case_priority',
            field=models.CharField(blank=True, choices=[('P0', '冒烟用例'), ('P1', '系统的重要功能用例'), ('P2', '系统的一般功能用例'), ('P3', '极低级别的用例')], default='P1', max_length=10, null=True, verbose_name='用例优先级'),
        ),
    ]
