# Generated by Django 2.0.5 on 2019-11-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0041_auto_20191011_1653'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaddandcheck',
            name='click_confirm_delay_time',
            field=models.CharField(blank=True, default='', help_text='点击确定按钮后的延时时长（单位秒），请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='点击确定按钮后的延时时长（单位秒）'),
        ),
    ]
