# Generated by Django 2.0.5 on 2019-11-08 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0043_auto_20191105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='newaddandcheck',
            name='depend_new_add_and_check_case',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景的用例'),
        ),
    ]
