# Generated by Django 2.0.5 on 2019-11-12 15:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0044_newaddandcheck_depend_new_add_and_check_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='IframeBodyInputText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iframe_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='iframe查找风格')),
                ('iframe_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='iframe查找风格的确切值')),
                ('input_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='输入框查找风格')),
                ('input_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='输入框查找风格的确切值')),
                ('is_auto_input', models.BooleanField(default=False, verbose_name='是否自动输入')),
                ('auto_input_type', models.CharField(blank=True, choices=[('1', '数字'), ('2', '字母（小写）'), ('3', '字母（大写）'), ('4', '特殊符号'), ('5', '数字和字母（小写）'), ('6', '数字和字母（大写）'), ('7', '字母（大小写）'), ('8', '数字和字母（大小写）'), ('9', '数字和字母和特殊符号'), ('10', '数字和字母和特殊符号和空白字符'), ('11', '汉字'), ('12', '手机号'), ('13', '身份证号')], default='11', max_length=10, null=True, verbose_name='自动输入字符的类型')),
                ('auto_input_long', models.CharField(blank=True, default='300', help_text='字符的个数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='自动输入的字符的个数')),
                ('input_text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='输入框中要输入的内容')),
                ('is_with_time', models.BooleanField(default=True, verbose_name='是否带时间串')),
                ('is_check', models.BooleanField(default=True, verbose_name='是否进行验证')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('newaddandcheck', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.NewAddAndCheck', verbose_name='依赖的添加场景')),
            ],
            options={
                'verbose_name': '富文本输入框相关内容',
                'verbose_name_plural': '富文本输入框相关内容',
            },
        ),
    ]
