# Generated by Django 2.0.5 on 2019-11-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0045_iframebodyinputtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newaddandcheck',
            name='click_confirm_delay_time',
            field=models.CharField(blank=True, default='3', help_text='点击确定按钮后的延时时长（单位秒），请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='点击确定按钮后的延时时长（单位秒）'),
        ),
    ]
