# Generated by Django 2.0.5 on 2019-11-21 10:28

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testdatas', '0046_auto_20191119_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteAndCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_project', models.CharField(default='', max_length=100, verbose_name='测试项目')),
                ('test_module', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='测试模块')),
                ('test_page', models.CharField(default='', max_length=100, verbose_name='测试页面')),
                ('case_priority', models.CharField(blank=True, choices=[('P0', '冒烟用例'), ('P1', '系统的重要功能用例'), ('P2', '系统的一般功能用例'), ('P3', '极低级别的用例')], default='P1', max_length=10, null=True, verbose_name='用例优先级')),
                ('test_case_title', models.CharField(default='', max_length=200, verbose_name='测试内容的名称')),
                ('is_run_case', models.BooleanField(default=True, verbose_name='是否运行')),
                ('delete_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='被删除元素查找风格')),
                ('delete_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='被删除元素查找风格的确切值')),
                ('confirm_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='删除弹框确定按钮查找风格')),
                ('confirm_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='删除弹框确定按钮查找风格的确切值')),
                ('click_confirm_delay_time', models.CharField(blank=True, default='3', help_text='点击确定按钮后的延时时长（单位秒），请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='点击确定按钮后的延时时长（单位秒）')),
                ('is_click_cancel', models.BooleanField(default=False, verbose_name='是否点击取消按钮')),
                ('cancel_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='删除弹框取消按钮查找风格')),
                ('cancel_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='删除弹框取消按钮查找风格的确切值')),
                ('is_submit_success', models.BooleanField(default=True, verbose_name='是否删除成功')),
                ('popup_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='删除成功弹框中的某个元素查找风格')),
                ('popup_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='删除成功弹框中的某个元素查找风格的确切值')),
                ('popup_text', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='删除成功弹框中的某个元素文本信息内容')),
                ('is_signel_page', models.BooleanField(default=True, verbose_name='是否单页面')),
                ('page_number_xpath', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='页数层xpath路径值')),
                ('result_table_ele_find', models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='结果表格查找风格')),
                ('result_table_ele_find_value', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='结果表格查找风格的确切值')),
                ('table_colnum_counts', models.CharField(blank=True, default='', help_text='结果表格总列数，请填写数字，例如：1、2、3', max_length=100, null=True, verbose_name='结果表格总列数')),
                ('case_counts', models.IntegerField(default='1', help_text='循环次数，请填写数字，例如：1、2、3', verbose_name='循环次数')),
                ('add_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='添加时间')),
                ('update_time', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='更新时间')),
                ('depend_click_case', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.ClickAndBack', verbose_name='依赖的点击场景的用例')),
                ('write_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='添加人')),
            ],
            options={
                'verbose_name': '新增场景',
                'verbose_name_plural': '新增场景',
            },
        ),
    ]
