# Generated by Django 2.0.5 on 2019-11-21 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0047_deleteandcheck'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleteandcheck',
            options={'verbose_name': '删除场景', 'verbose_name_plural': '删除场景'},
        ),
    ]
