# Generated by Django 2.0.5 on 2019-11-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0048_auto_20191121_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='deleteandcheck',
            name='delete_button_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='删除按钮查找风格'),
        ),
        migrations.AddField(
            model_name='deleteandcheck',
            name='delete_button_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='删除按钮查找风格的确切值'),
        ),
    ]
