# Generated by Django 2.0.5 on 2019-11-22 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0050_auto_20191121_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editandcheck',
            name='is_signel_page',
            field=models.BooleanField(default=True, verbose_name='是否单页面'),
        ),
    ]
