# Generated by Django 2.0.5 on 2019-11-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0051_auto_20191122_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputtapinputtext',
            name='clear_icon_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='清除图标查找风格'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='clear_icon_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='清除图标查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='is_click_clear_icon',
            field=models.BooleanField(default=False, verbose_name='是否点击清空图标'),
        ),
        migrations.AddField(
            model_name='selecttapselectoption',
            name='clear_icon_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='清除图标查找风格'),
        ),
        migrations.AddField(
            model_name='selecttapselectoption',
            name='clear_icon_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='清除图标查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='selecttapselectoption',
            name='is_click_clear_icon',
            field=models.BooleanField(default=False, verbose_name='是否点击清空图标'),
        ),
    ]
