# Generated by Django 2.0.5 on 2019-11-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0052_auto_20191122_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='clear_icon_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='清空图标查找风格'),
        ),
        migrations.AlterField(
            model_name='inputtapinputtext',
            name='clear_icon_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='清空图标查找风格的确切值'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='clear_icon_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='清空图标查找风格'),
        ),
        migrations.AlterField(
            model_name='selecttapselectoption',
            name='clear_icon_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='清空图标查找风格的确切值'),
        ),
    ]
