# Generated by Django 2.0.5 on 2019-11-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0054_auto_20191125_1706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asserttiptext',
            name='loginandcheck',
        ),
        migrations.RemoveField(
            model_name='inputtapinputtext',
            name='loginandcheck',
        ),
    ]
