# Generated by Django 2.0.5 on 2019-11-28 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0057_auto_20191128_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='asserttiptext',
            name='loginandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.LoginAndCheck', verbose_name='依赖的登录场景'),
        ),
        migrations.AddField(
            model_name='inputtapinputtext',
            name='loginandcheck',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.PROTECT, to='testdatas.LoginAndCheck', verbose_name='依赖的登录场景'),
        ),
    ]
