# Generated by Django 2.0.5 on 2019-11-28 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0058_auto_20191128_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginandcheck',
            name='code_image_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='验证码查找风格'),
        ),
        migrations.AddField(
            model_name='loginandcheck',
            name='code_image_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='验证码查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='loginandcheck',
            name='code_input_ele_find',
            field=models.CharField(blank=True, default='xpath', help_text='元素查找风格：id、name、class_name、tag_name、link_text、partial_link_text、css_selector、xpath', max_length=100, null=True, verbose_name='验证码输入框查找风格'),
        ),
        migrations.AddField(
            model_name='loginandcheck',
            name='code_input_ele_find_value',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='验证码输入框查找风格的确切值'),
        ),
        migrations.AddField(
            model_name='loginandcheck',
            name='is_auto_input_code',
            field=models.BooleanField(default=False, verbose_name='是否自动输入验证码'),
        ),
    ]
