# Generated by Django 2.0.5 on 2019-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdatas', '0061_selecttapselectoption_is_multiple_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickandback',
            name='is_static_load_page_time',
            field=models.BooleanField(default=False, verbose_name='是否统计页面加载时间'),
        ),
    ]
